import { memo, useCallback, useEffect, useMemo, useState, useSyncExternalStore } from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import { useAppDispatch, useAppSelector } from "../../store/hooks";
import {
  selectComposer,
  setContent,
  setHashtagMode,
  setHashtags,
  setLanguage,
  setSubreddit,
  setTitle,
  toggleAccount,
  toggleImage,
  removeImage,
  uploadImages,
  fetchComposerData,
  generatePostImage,
} from "../../store/slices/composerSlice";
import { selectToken } from "../../store/slices/authSlice";
import { selectAccounts, fetchAccounts } from "../../store/slices/accountsSlice";
import { mergePlatformAccounts } from "../../lib/platformAccounts";
import { getComposerDraft, subscribeComposerDraft } from "../../lib/composerDraft";
import { ContentEditor } from "./ContentEditor";
import { ComposeAssistToggles, useComposeAssistPrefs } from "./ComposeAssistToggles";
import { HashtagInput } from "./HashtagInput";
import { HashtagOptions } from "./HashtagOptions";
import { ImagePicker } from "./ImagePicker";
import { RedditFields } from "./RedditFields";
import { AiAssistPanel } from "./AiAssistPanel";
import { AutoGenerateImageToggle } from "./AutoGenerateImageToggle";
import { ConnectionErrorAlert } from "../accounts/ConnectionErrorAlert";
import { ComposerPlatformGrid } from "./ComposerPlatformGrid";
import { ComposerPublishPanel } from "./ComposerPublishPanel";
import { api } from "../../lib/api";
import {
  COMPOSE_AUTO_IMAGE_KEY,
  readComposePref,
  writeComposePref,
} from "../../lib/composeAssistPrefs";
import { useComposeTheme } from "./composeTheme";
import type { ReactNode } from "react";
import type { SxProps, Theme } from "@mui/material/styles";

const MIN_CONTENT_FOR_AUTO_IMAGE = 40;
const AUTO_IMAGE_DEBOUNCE_MS = 2800;

function ComposeSection({
  title,
  description,
  action,
  children,
  sx,
}: {
  title: string;
  description?: string;
  action?: ReactNode;
  children: ReactNode;
  sx?: SxProps<Theme>;
}) {
  const { colors, fonts } = useComposeTheme();

  return (
    <Box
      sx={{
        bgcolor: colors.surface,
        border: "1px solid",
        borderColor: colors.border,
        borderRadius: "16px",
        p: "22px",
        mb: "18px",
        boxShadow: "0 1px 2px rgba(16,24,40,0.03)",
        ...sx,
      }}
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "space-between",
          gap: 1.5,
          mb: 2,
          flexWrap: "wrap",
        }}
      >
        <Box>
          <Typography
            sx={{
              fontFamily: fonts.heading,
              fontSize: 15.5,
              fontWeight: 700,
              color: colors.textPrimary,
              lineHeight: 1.3,
              mb: description ? 0.375 : 0,
            }}
          >
            {title}
          </Typography>
          {description && (
            <Typography
              sx={{
                fontSize: 13,
                color: colors.textSecondary,
                fontFamily: fonts.body,
                lineHeight: 1.45,
              }}
            >
              {description}
            </Typography>
          )}
        </Box>
        {action}
      </Box>
      {children}
    </Box>
  );
}

export const ComposerFormPanel = memo(function ComposerFormPanel() {
  const { colors, fonts, fieldLabelSx, selectSx } = useComposeTheme();
  const dispatch = useAppDispatch();
  const token = useAppSelector(selectToken);
  const draft = useSyncExternalStore(subscribeComposerDraft, getComposerDraft);
  const {
    content,
    title,
    subreddit,
    hashtagMode,
    hashtags,
    language,
    images,
    options,
    accounts,
    selectedAccounts,
    mediaLibrary,
    imageWarnings,
    uploadError,
    uploading,
    generatingImage,
    generateImageError,
    autoGeneratedImageUrl,
    lastAutoImageContent,
    initialized,
    error: composerError,
  } = useAppSelector(selectComposer);
  const { items: accountsFromSlice, loading: accountsLoading, error: accountsError } =
    useAppSelector(selectAccounts);

  const handleSyncContent = useCallback(
    (value: string) => dispatch(setContent(value)),
    [dispatch],
  );

  const handleUpload = useCallback(
    (files: FileList) => dispatch(uploadImages(Array.from(files))),
    [dispatch],
  );

  const platformAccounts = mergePlatformAccounts(accounts, accountsFromSlice);

  const hasRedditSelected = selectedAccounts.some((id) => {
    const acc = platformAccounts.find((a) => a.id === id);
    return acc?.platform === "REDDIT";
  });

  const primaryPlatform =
    selectedAccounts.length > 0
      ? platformAccounts.find((a) => a.id === selectedAccounts[0])?.platform
      : platformAccounts[0]?.platform;

  const { smartSuggest, autoCorrect, setSmartSuggest, setAutoCorrect } =
    useComposeAssistPrefs();
  const [aiConfigured, setAiConfigured] = useState(false);
  const [aiImageAvailable, setAiImageAvailable] = useState(false);
  const [autoGenerateImage, setAutoGenerateImage] = useState(() =>
    readComposePref(COMPOSE_AUTO_IMAGE_KEY, false),
  );

  const selectedPlatformNames = useMemo(
    () =>
      selectedAccounts
        .map((id) => platformAccounts.find((a) => a.id === id)?.platform)
        .filter((p): p is string => Boolean(p)),
    [selectedAccounts, platformAccounts],
  );

  useEffect(() => {
    if (!token) return;
    const total = accounts.length > 0 ? accounts.length : accountsFromSlice.length;
    if (total === 0 && initialized && !accountsLoading) {
      dispatch(fetchAccounts());
      dispatch(fetchComposerData());
    }
  }, [
    token,
    accounts.length,
    accountsFromSlice.length,
    initialized,
    accountsLoading,
    dispatch,
  ]);

  useEffect(() => {
    if (!token) return;
    api
      .getAiStatus(token)
      .then((s) => {
        setAiConfigured(s.configured);
        setAiImageAvailable(Boolean(s.imageGeneration));
      })
      .catch(() => {
        setAiConfigured(false);
        setAiImageAvailable(false);
      });
  }, [token]);

  const triggerGenerateImage = useCallback(() => {
    const trimmed = content.trim();
    if (trimmed.length < MIN_CONTENT_FOR_AUTO_IMAGE) return;
    dispatch(
      generatePostImage({
        content: trimmed,
        language,
        platform: primaryPlatform,
        replaceUrl: autoGeneratedImageUrl,
      }),
    );
  }, [content, language, primaryPlatform, autoGeneratedImageUrl, dispatch]);

  useEffect(() => {
    if (!autoGenerateImage || !aiImageAvailable || !aiConfigured) return;

    const trimmed = content.trim();
    if (trimmed.length < MIN_CONTENT_FOR_AUTO_IMAGE) return;
    if (generatingImage || uploading) return;

    const hasManualImages = images.some((url) => url !== autoGeneratedImageUrl);
    if (hasManualImages) return;

    if (trimmed === lastAutoImageContent && autoGeneratedImageUrl) return;

    const timer = window.setTimeout(() => {
      triggerGenerateImage();
    }, AUTO_IMAGE_DEBOUNCE_MS);

    return () => window.clearTimeout(timer);
  }, [
    autoGenerateImage,
    aiImageAvailable,
    aiConfigured,
    content,
    generatingImage,
    uploading,
    images,
    autoGeneratedImageUrl,
    lastAutoImageContent,
    triggerGenerateImage,
  ]);

  const charCount = draft.length;
  const twitterSelected = selectedPlatformNames.includes("TWITTER");

  const tagPreview = useMemo(() => {
    if (hashtagMode === "manual") return hashtags;
    if (hashtagMode === "none") return [];
    return hashtags;
  }, [hashtagMode, hashtags]);

  return (
    <Box>
      <ComposeSection title="Content" description="Write your text, or send an image on its own.">
        <ContentEditor
          value={content}
          onSync={handleSyncContent}
          placeholder="What do you want to share?"
          language={language}
          token={token}
          aiConfigured={aiConfigured}
          smartSuggest={smartSuggest}
          autoCorrect={autoCorrect}
          composeTheme
        />
        <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mt: 1 }}>
          <Typography
            sx={{
              fontFamily: fonts.mono,
              fontSize: 11.5,
              color: twitterSelected && charCount > 280 ? colors.danger : colors.textTertiary,
              fontWeight: twitterSelected && charCount > 280 ? 600 : 400,
            }}
          >
            {charCount} character{charCount === 1 ? "" : "s"}
          </Typography>
          <Box
            sx={{
              width: 8,
              height: 8,
              borderRadius: "50%",
              bgcolor: colors.success,
              boxShadow: `0 0 0 3px ${colors.successSoft}`,
            }}
            title="Ready to publish"
          />
        </Box>
        <ComposeAssistToggles
          aiConfigured={aiConfigured}
          smartSuggest={smartSuggest}
          autoCorrect={autoCorrect}
          onSmartSuggestChange={setSmartSuggest}
          onAutoCorrectChange={setAutoCorrect}
        />
        <AiAssistPanel
          token={token}
          content={content}
          language={language}
          platform={primaryPlatform}
          onContentChange={(value) => dispatch(setContent(value))}
          onHashtagsChange={(tags) => dispatch(setHashtags(tags))}
          onHashtagModeChange={(mode) => dispatch(setHashtagMode(mode))}
        />
      </ComposeSection>

      {hasRedditSelected && (
        <ComposeSection title="Reddit" description="Title and subreddit are required for Reddit posts.">
          <RedditFields
            title={title}
            subreddit={subreddit}
            onTitleChange={(v) => dispatch(setTitle(v))}
            onSubredditChange={(v) => dispatch(setSubreddit(v))}
          />
        </ComposeSection>
      )}

      <ComposeSection title="Hashtags" description="Auto-generate, write your own, or skip them entirely.">
        <HashtagOptions
          value={hashtagMode}
          onChange={(mode) => dispatch(setHashtagMode(mode))}
          options={options.hashtagModes}
        />
        {hashtagMode === "manual" && (
          <HashtagInput tags={hashtags} onChange={(tags) => dispatch(setHashtags(tags))} />
        )}
        {tagPreview.length > 0 && (
          <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.75, mt: 1.25 }}>
            {tagPreview.map((tag) => (
              <Box
                key={tag}
                component="span"
                sx={{
                  fontFamily: fonts.mono,
                  fontSize: 11.5,
                  color: colors.accent,
                  bgcolor: colors.accentSoft,
                  px: "9px",
                  py: "4px",
                  borderRadius: 999,
                }}
              >
                #{tag}
              </Box>
            ))}
          </Box>
        )}
      </ComposeSection>

      <ComposeSection title="Language" description="Post text and hashtags will be shown in this language.">
        <Typography component="label" sx={fieldLabelSx}>
          Post language
        </Typography>
        <Box
          component="select"
          value={language}
          onChange={(e: React.ChangeEvent<HTMLSelectElement>) => dispatch(setLanguage(e.target.value))}
          sx={selectSx}
        >
          {options.languages.map((lang) => (
            <option key={lang.code} value={lang.code}>
              {lang.label}
            </option>
          ))}
        </Box>
      </ComposeSection>

      <ComposeSection
        title="Images"
        description="LinkedIn recommends 1200×627 or 1200×1200 · min 552×276px · max 8MB · ratio 4:5 to 1.91:1"
      >
        <Box sx={{ mb: 2 }}>
          <AutoGenerateImageToggle
            enabled={autoGenerateImage}
            available={aiImageAvailable}
            aiConfigured={aiConfigured}
            generating={generatingImage}
            error={generateImageError}
            hasContent={content.trim().length >= MIN_CONTENT_FOR_AUTO_IMAGE}
            onEnabledChange={(value) => {
              setAutoGenerateImage(value);
              writeComposePref(COMPOSE_AUTO_IMAGE_KEY, value);
            }}
            onGenerateNow={triggerGenerateImage}
          />
        </Box>
        <ImagePicker
          images={images}
          mediaLibrary={mediaLibrary}
          token={token}
          uploading={uploading || generatingImage}
          uploadError={uploadError}
          imageWarnings={imageWarnings}
          onUpload={handleUpload}
          onToggle={(url) => dispatch(toggleImage(url))}
          onRemove={(url) => dispatch(removeImage(url))}
          composeTheme
        />
      </ComposeSection>

      <ComposeSection title="Platforms" description="Select where to publish — multiple selection cross-posts to all.">
        <ConnectionErrorAlert
          accounts={platformAccounts}
          selectedAccountIds={selectedAccounts}
        />
        {accountsLoading && platformAccounts.length === 0 && (
          <Typography sx={{ fontSize: 12.5, color: colors.textSecondary, mb: 1.5, fontFamily: fonts.body }}>
            Loading connected accounts…
          </Typography>
        )}
        {accountsError && platformAccounts.length === 0 && (
          <Typography sx={{ fontSize: 12.5, color: colors.danger, mb: 1.5, fontFamily: fonts.body }}>
            {accountsError} — backend chal raha hai? Logout karke dubara login try karo.
          </Typography>
        )}
        {composerError && accounts.length === 0 && platformAccounts.length === 0 && !accountsError && (
          <Typography sx={{ fontSize: 12.5, color: colors.danger, mb: 1.5, fontFamily: fonts.body }}>
            Could not load connected accounts. Refresh the page or check that the backend is running.
          </Typography>
        )}
        <ComposerPlatformGrid
          accounts={platformAccounts}
            selectedAccounts={selectedAccounts}
            onToggle={(id) => dispatch(toggleAccount(id))}
          />
      </ComposeSection>

      <ComposeSection
        title="Publish or schedule"
        description="One action panel — no duplicate submissions."
        sx={{
          position: { xs: "sticky", md: "static" },
          bottom: { xs: 12, md: "auto" },
          zIndex: { xs: 2, md: "auto" },
          boxShadow: {
            xs: "0 -8px 24px rgba(16,24,40,0.08)",
            md: "0 1px 2px rgba(16,24,40,0.03)",
          },
        }}
      >
        <ComposerPublishPanel />
      </ComposeSection>
    </Box>
  );
});
